import pytest
import base64
from pathlib import Path
from backend.app.api.routes.library import extract_gcode_thumbnail

SAMPLE_GCODE_WITH_THUMBNAIL = """
; generated by OrcaSlicer 2.1.0
; HEADER_BLOCK_START
; total_page_number = 1
; estimated printing time (normal mode) = 45m 12s
; total filament used [g] = 18.5
; layer_height = 0.20
; nozzle_diameter = 0.40
; HEADER_BLOCK_END
;
; thumbnail begin 160x160 1234
; iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==
; thumbnail end
;
G28 ; Home all axes
G1 Z0.2 F3000
"""

def test_extract_gcode_thumbnail_raw_bytes():
    thumb_bytes = extract_gcode_thumbnail(SAMPLE_GCODE_WITH_THUMBNAIL.encode("utf-8"))
    assert thumb_bytes is not None
    assert isinstance(thumb_bytes, bytes)
    # Check PNG magic header
    assert thumb_bytes.startswith(b"\x89PNG")

def test_extract_gcode_thumbnail_file(tmp_path):
    gcode_file = tmp_path / "test.gcode"
    gcode_file.write_text(SAMPLE_GCODE_WITH_THUMBNAIL)
    
    thumb_bytes = extract_gcode_thumbnail(gcode_file)
    assert thumb_bytes is not None
    assert thumb_bytes.startswith(b"\x89PNG")
